# Use container on EC2, other options available
# (venvs)[https://docs.travis-ci.com/user/reference/overview/]
dist: xenial

notifications:
  email: false

git:
  depth: 5
  submodules: false

language: python

cache:
  - pip
  - directories:
    - doc/sphinx_gallery_auto
#    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.8-dev'

env:
  global:
    - MAKEFLAGS='-j 2'  # This allows to parallelise make, e.g. make t1 t2
  matrix:
    - FATF_TEST_SCIPY=1.3.0  FATF_TEST_NUMPY=1.16.3
    - FATF_TEST_SCIPY=1.2.0  FATF_TEST_NUMPY=1.16.0
    - FATF_TEST_SCIPY=1.1.0  FATF_TEST_NUMPY=1.15.4
    - FATF_TEST_SCIPY=1.0.1  FATF_TEST_NUMPY=1.14.6
    - FATF_TEST_SCIPY=0.19.1 FATF_TEST_NUMPY=1.13.3
    - FATF_TEST_SCIPY=0.18.1 FATF_TEST_NUMPY=1.12.1
    # The matplotlib version is fixed to 3.0.0 because since version 3.1 it
    # requires at least 1.11 numpy and we support numpy 1.10
    - FATF_TEST_SCIPY=0.18.1 FATF_TEST_NUMPY=1.10.1 FATF_TEST_MATPLOTLIB=3.0.0
    - FATF_TEST_SCIPY=latest FATF_TEST_NUMPY=latest

matrix:
  fast_finish: true
  exclude:
    - python: '3.7'
      env: FATF_TEST_SCIPY=1.0.1  FATF_TEST_NUMPY=1.14.6
    - python: '3.7'
      env: FATF_TEST_SCIPY=0.19.1 FATF_TEST_NUMPY=1.13.3
    - python: '3.7'
      env: FATF_TEST_SCIPY=0.18.1 FATF_TEST_NUMPY=1.12.1
    - python: '3.7'
      env: FATF_TEST_SCIPY=0.18.1 FATF_TEST_NUMPY=1.10.1 FATF_TEST_MATPLOTLIB=3.0.0
    - python: '3.8-dev'
      env: FATF_TEST_SCIPY=1.0.1  FATF_TEST_NUMPY=1.14.6
    - python: '3.8-dev'
      env: FATF_TEST_SCIPY=0.19.1 FATF_TEST_NUMPY=1.13.3
    - python: '3.8-dev'
      env: FATF_TEST_SCIPY=0.18.1 FATF_TEST_NUMPY=1.12.1
    - python: '3.8-dev'
      env: FATF_TEST_SCIPY=0.18.1 FATF_TEST_NUMPY=1.10.1 FATF_TEST_MATPLOTLIB=3.0.0
  allow_failures:
    - python: '3.8-dev'
    - env: FATF_TEST_SCIPY=latest FATF_TEST_NUMPY=latest

install:
  # lime has to be installed before anything else since we overwrite its deps
  - make install-lime
  - make install-matplotlib
  - make dependencies-dev  # Install python development dependencies
#  - pip install scikit-learn
#  - make install-sans-dep

before_script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]] && \
       [[ "$FATF_TEST_SCIPY" == "1.3.0" ]] && \
       [[ "$FATF_TEST_NUMPY" == "1.16.3" ]]; then
      TRAVIS_TEST_DOCUMENTATION=1
    else
      TRAVIS_TEST_DOCUMENTATION=0
    fi

script:
  - make linting-pylint
  - make linting-flake8
  - make linting-yapf
  - make check-types
  - make test-with-code-coverage
#  - make test-notebooks
  - if [[ $TRAVIS_TEST_DOCUMENTATION == 1 ]]; then make test-doc; fi
#  - if [[ $TRAVIS_TEST_DOCUMENTATION == 1 ]]; then make doc-linkcheck; fi
  - if [[ $TRAVIS_TEST_DOCUMENTATION == 1 ]]; then make doc-coverage; fi

jobs:
  include:
    - stage: Documentation Deployment
      python: 3.6
      if: |
        env(FATF_TEST_SCIPY) = 1.3.0 AND \
        env(FATF_TEST_NUMPY) = 1.16.3 AND \
        fork = false AND \
        branch = dev AND \
        type = push
      before_deploy:
        - make doc-html
      deploy:
        provider: script
        script: bash build_tools/doc/deploy-doc.sh dev
        skip_cleanup: true
        on:
          branch: dev
